import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: hashSync("123456", 10), //a salt (10) is a random value to make it more secure, even if 2 people have the same password
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Round Cake Pan 25X7.5 Cm",
      slug: "0400123",
      category: "Alas Kue",
      description:
        "Round Cake Pan 25X7.5 Cm made with durable materials. Ideal for home and professional use.",
      price: 27.96,
      brand: "Surya Indometal",
      rating: 4.5,
      numReviews: 11,
      stock: 16,
      isFeatured: false,
      banner: "/images/surya-products/0400123.jpg",
      images: ["/images/surya-products/0400123.jpg"],
    },
    {
      name: "Flower Nail (5)",
      slug: "0400478",
      category: "Alat Dekorasi",
      description:
        "Flower Nail (5) made with durable materials. Ideal for home and professional use.",
      price: 56.79,
      brand: "Surya Indometal",
      rating: 4.0,
      numReviews: 86,
      stock: 37,
      isFeatured: true,
      banner: "/images/surya-products/0400478.jpg",
      images: ["/images/surya-products/0400478.jpg"],
    },
    {
      name: "Revolving Cake Stand 300X35Mm",
      slug: "0400302",
      category: "Alat Dekorasi",
      description:
        "Revolving Cake Stand 300X35Mm made with durable materials. Ideal for home and professional use.",
      price: 27.17,
      brand: "Surya Indometal",
      rating: 3.8,
      numReviews: 11,
      stock: 18,
      isFeatured: true,
      banner: "/images/surya-products/0400302.jpg",
      images: ["/images/surya-products/0400302.jpg"],
    },
    {
      name: "Brioche 6 Wave Mold",
      slug: "0400082",
      category: "Cetakan Kue",
      description:
        "Brioche 6 Wave Mold made with durable materials. Ideal for home and professional use.",
      price: 18.33,
      brand: "Surya Indometal",
      rating: 4.1,
      numReviews: 52,
      stock: 50,
      isFeatured: true,
      banner: "/images/surya-products/0400082.jpg",
      images: ["/images/surya-products/0400082.jpg"],
    },
    {
      name: "Brioche 7X1.7 Cm",
      slug: "0400069",
      category: "Cetakan Kue",
      description:
        "Brioche 7X1.7 Cm made with durable materials. Ideal for home and professional use.",
      price: 54.3,
      brand: "Surya Indometal",
      rating: 4.2,
      numReviews: 56,
      stock: 0,
      isFeatured: false,
      banner: "/images/surya-products/0400069.jpg",
      images: ["/images/surya-products/0400069.jpg"],
    },
    {
      name: "Brioche 8.5X2.5 Cm",
      slug: "0400070",
      category: "Cetakan Kue",
      description:
        "Brioche 8.5X2.5 Cm made with durable materials. Ideal for home and professional use.",
      price: 55.0,
      brand: "Surya Indometal",
      rating: 4.4,
      numReviews: 91,
      stock: 0,
      isFeatured: false,
      banner: "/images/surya-products/0400070.jpg",
      images: ["/images/surya-products/0400070.jpg"],
    },
    {
      name: "Cup Mold(12)",
      slug: "0400055",
      category: "Cetakan Kue",
      description:
        "Cup Mold(12) made with durable materials. Ideal for home and professional use.",
      price: 11.94,
      brand: "Surya Indometal",
      rating: 4.0,
      numReviews: 66,
      stock: 5,
      isFeatured: true,
      banner: "/images/surya-products/0400055.jpg",
      images: ["/images/surya-products/0400055.jpg"],
    },
    {
      name: "Leaf Mold(12)",
      slug: "0400116",
      category: "Cetakan Kue",
      description:
        "Leaf Mold(12) made with durable materials. Ideal for home and professional use.",
      price: 17.53,
      brand: "Surya Indometal",
      rating: 5.0,
      numReviews: 43,
      stock: 0,
      isFeatured: false,
      banner: "/images/surya-products/0400116.jpg",
      images: ["/images/surya-products/0400116.jpg"],
    },
    {
      name: "Mini Chiffon Cake 10.7X5 Cm",
      slug: "0400079",
      category: "Cetakan Kue",
      description:
        "Mini Chiffon Cake 10.7X5 Cm made with durable materials. Ideal for home and professional use.",
      price: 39.31,
      brand: "Surya Indometal",
      rating: 4.9,
      numReviews: 14,
      stock: 44,
      isFeatured: true,
      banner: "/images/surya-products/0400079.jpg",
      images: ["/images/surya-products/0400079.jpg"],
    },
    {
      name: "Mini Croissant Cutter Single D 6X8 Cm",
      slug: "0400207",
      category: "Cetakan Kue",
      description:
        "Mini Croissant Cutter Single D 6X8 Cm made with durable materials. Ideal for home and professional use.",
      price: 41.45,
      brand: "Surya Indometal",
      rating: 3.7,
      numReviews: 30,
      stock: 6,
      isFeatured: false,
      banner: "/images/surya-products/0400207.jpg",
      images: ["/images/surya-products/0400207.jpg"],
    },
  ],
};

export default sampleData;
